<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>@yield('title', 'Xavier Report')</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1a202c; margin: 0; padding: 20px; font-size: 12px; }
        .header { border-bottom: 2px solid #e2e8f0; padding-bottom: 15px; margin-bottom: 20px; }
        .header table { width: 100%; }
        .brand { font-size: 20px; font-weight: bold; color: #0f172a; text-transform: uppercase; }
        .meta { text-align: right; color: #64748b; font-size: 10px; }
        .summary-cards { margin-bottom: 20px; width: 100%; }
        .card { background: #f8fafc; border: 1px solid #e2e8f0; padding: 10px; border-radius: 4px; }
        .card-title { font-size: 9px; text-transform: uppercase; color: #64748b; margin-bottom: 4px; }
        .card-value { font-size: 14px; font-weight: bold; color: #0f172a; }
        table.data-table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        table.data-table th { background: #f1f5f9; color: #475569; text-align: left; padding: 8px; font-size: 10px; text-transform: uppercase; border-bottom: 1px solid #cbd5e1; }
        table.data-table td { padding: 8px; border-bottom: 1px solid #e2e8f0; font-size: 11px; }
        .text-right { text-align: right; }
        .footer { position: fixed; bottom: 0; width: 100%; font-size: 9px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <table>
            <tr>
                <td class="brand">Xavier Platform</td>
                <td class="meta">
                    <strong>Report:</strong> @yield('report_name')<br>
                    <strong>Generated:</strong> {{ now()->format('Y-m-d H:i:s') }}<br>
                    <strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}
                </td>
            </tr>
        </table>
    </div>

    @yield('content')

    <div class="footer">
        Confidential - Xavier Executive Reporting System &bull; Page 1 of 1
    </div>
</body>
</html>