<?php

namespace App\Notifications;

use App\Models\User;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Illuminate\Support\Facades\Log;

class ReportGeneratedNotification extends Notification implements ShouldQueue
{
    use Queueable;

    protected User $user;
    protected ?string $fileName;
    protected ?string $fileContent;
    protected ?string $mimeType;
    protected string $from;
    protected string $to;
    protected string $reportType;
    protected ?string $message;
    protected ?User $admin;

    public function __construct(
        User $user,
        ?string $fileName,
        ?string $fileContent,
        ?string $mimeType,
        string $from,
        string $to,
        string $reportType = 'account_statement',
        ?string $message = null,
        ?User $admin = null
    ) {
        $this->user = $user;
        $this->fileName = $fileName;
        $this->fileContent = $fileContent;
        $this->mimeType = $mimeType;
        $this->from = $from;
        $this->to = $to;
        $this->reportType = $reportType;
        $this->message = $message;
        $this->admin = $admin;
    }

    public function via(object $notifiable): array
    {
        return ['mail', 'database'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $reportLabel = $this->reportType === 'trading_performance' ? 'Trading Performance Report' : 'Account Statement';
        $adminName = $this->admin ? $this->admin->name : 'Xavier Admin';

        $mail = (new MailMessage)
            ->subject("Your {$reportLabel} is Ready - Xavier Trading Platform")
            ->greeting("Hello {$this->user->name},")
            ->line("A new {$reportLabel} has been generated for you by {$adminName}.")
            ->line("**Period:** {$this->from} to {$this->to}")
            ->line("**Format:** " . strtoupper(pathinfo($this->fileName, PATHINFO_EXTENSION)));

        if ($this->message) {
            $mail->line("**Message from Admin:**");
            $mail->line($this->message);
        }

        if ($this->fileContent && $this->fileName) {
            // Store in storage and attach path
            try {
                $storagePath = "reports/{$this->user->id}/{$this->fileName}";
                $directory = dirname(storage_path("app/{$storagePath}"));
                if (!is_dir($directory)) {
                    mkdir($directory, 0755, true);
                }
                file_put_contents(storage_path("app/{$storagePath}"), $this->fileContent);
                
                $mail->attach(storage_path("app/{$storagePath}"), [
                    'as' => $this->fileName,
                    'mime' => $this->mimeType,
                ]);
            } catch (\Exception $e) {
                Log::error('Failed to attach report to email: ' . $e->getMessage());
            }
        }

        return $mail
            ->line("Please review the attached document or log in to your Xavier dashboard to view it.")
            ->action('View Dashboard', url('/'))
            ->line('Thank you for using Xavier Trading Platform!');
    }

    public function toArray(object $notifiable): array
    {
        $reportLabel = $this->reportType === 'trading_performance' ? 'Trading Performance Report' : 'Account Statement';
        $adminName = $this->admin ? $this->admin->name : 'Xavier Admin';

        $data = [
            'title' => "{$reportLabel} Ready",
            'message' => "Your {$reportLabel} ({$this->from} to {$this->to}) has been generated by {$adminName}.",
            'type' => 'report_generated',
            'report_type' => $this->reportType,
            'from' => $this->from,
            'to' => $this->to,
            'format' => $this->fileName ? strtoupper(pathinfo($this->fileName, PATHINFO_EXTENSION)) : 'PDF',
        ];

        if ($this->message) {
            $data['admin_message'] = $this->message;
        }

        return $data;
    }
}