<template>
  <div class="space-y-6">
      <div class="flex items-center justify-between">
        <h1 class="text-xl font-bold text-white">Report Downloads</h1>
      </div>

      <div v-if="loading" class="space-y-6">
        <SkeletonLoader type="table" :count="5" />
      </div>

      <template v-else>
        <div class="bg-[#0F1724] border border-[#1f3348] rounded-xl overflow-hidden">
          <div class="flex flex-wrap items-center gap-3 p-3 border-b border-[#1f3348]">
            <select v-model="formatFilter" class="bg-[#1C2541] text-white text-xs rounded-lg px-3 py-2 border border-[#1f3348] focus:border-[#0047AB] outline-none">
              <option value="">All Formats</option>
              <option value="pdf">PDF</option>
              <option value="excel">Excel</option>
              <option value="csv">CSV</option>
            </select>
            <select v-model="statusFilter" class="bg-[#1C2541] text-white text-xs rounded-lg px-3 py-2 border border-[#1f3348] focus:border-[#0047AB] outline-none">
              <option value="">All Statuses</option>
              <option value="completed">Completed</option>
              <option value="pending">Pending</option>
              <option value="failed">Failed</option>
            </select>
            <button
              v-if="formatFilter || statusFilter"
              @click="resetFilters"
              class="px-2 py-2 text-xs font-medium rounded-lg transition-colors text-gray-400 hover:text-white hover:bg-[#1f3348]"
              title="Reset filters"
            >
              ✕ Reset
            </button>
          </div>
          <div class="overflow-x-auto">
            <table class="w-full text-sm">
              <thead>
                <tr class="border-b border-[#1f3348]">
                  <th class="px-4 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Report</th>
                  <th class="px-4 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Generated By</th>
                  <th class="px-4 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Format</th>
                  <th class="px-4 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Status</th>
                  <th class="px-4 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Created</th>
                  <th class="px-4 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr v-if="filteredHistory.length === 0">
                  <td colspan="6" class="px-4 py-8 text-center text-gray-500">
                    <EmptyState :message="history.data.length === 0 ? 'No reports have been downloaded yet' : 'No reports match your filters'" />
                  </td>
                </tr>
                <tr v-for="item in filteredHistory" :key="item.id" class="border-b border-[#1f3348] hover:bg-[#1C2541] transition-colors">
                  <td class="px-4 py-3 text-white font-medium">{{ item.name }}</td>
                  <td class="px-4 py-3 text-gray-300">{{ item.user?.name || 'N/A' }}</td>
                  <td class="px-4 py-3">
                    <span class="px-2 py-0.5 rounded-full text-xs font-medium uppercase" :class="getFormatClass(item.format)">{{ item.format }}</span>
                  </td>
                  <td class="px-4 py-3">
                    <span class="px-2 py-0.5 rounded-full text-xs font-medium" :class="item.status === 'completed' ? 'bg-green-900/50 text-green-400' : 'bg-yellow-900/50 text-yellow-400'">{{ item.status }}</span>
                  </td>
                  <td class="px-4 py-3 text-gray-400">{{ formatDate(item.created_at) }}</td>
                  <td class="px-4 py-3">
                    <div class="flex items-center gap-2">
                      <button v-if="item.status === 'completed'" @click="downloadReport(item)" class="flex items-center gap-1 px-2 py-1 text-xs font-medium text-white bg-[#0047AB] hover:bg-[#003580] rounded-lg transition-colors">
                        <Download class="w-3 h-3" /> Download
                      </button>
                      <button @click="deleteReport(item.id)" class="flex items-center gap-1 px-2 py-1 text-xs font-medium text-red-400 hover:bg-red-900/30 rounded-lg transition-colors">
                        <Trash2 class="w-3 h-3" /> Delete
                      </button>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div v-if="history.total > history.per_page" class="flex items-center justify-between px-4 py-3 border-t border-[#1f3348]">
            <span class="text-xs text-gray-500">Showing {{ history.from }} - {{ history.to }} of {{ history.total }}</span>
            <div class="flex items-center gap-1">
              <button @click="changePage(history.current_page - 1)" :disabled="!history.prev_page_url" class="px-2 py-1 text-xs rounded hover:bg-[#1C2541] disabled:opacity-50 disabled:cursor-not-allowed">
                <ChevronLeft class="w-4 h-4" />
              </button>
              <span class="px-2 py-1 text-xs text-white">{{ history.current_page }}</span>
              <button @click="changePage(history.current_page + 1)" :disabled="!history.next_page_url" class="px-2 py-1 text-xs rounded hover:bg-[#1C2541] disabled:opacity-50 disabled:cursor-not-allowed">
                <ChevronRight class="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>
      </template>
    </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import EmptyState from '@/Components/Reports/EmptyState.vue';
import SkeletonLoader from '@/Components/SkeletonLoader.vue';
import { Download, Trash2, ChevronLeft, ChevronRight } from 'lucide-vue-next';
import api from '@/api';

const loading = ref(true);
const history = ref({ data: [], total: 0, per_page: 20, current_page: 1, from: 0, to: 0, prev_page_url: null, next_page_url: null });

const formatFilter = ref('');
const statusFilter = ref('');

const filteredHistory = computed(() =>
  history.value.data.filter((item) => {
    if (formatFilter.value && (item.format || '').toLowerCase() !== formatFilter.value.toLowerCase()) return false;
    if (statusFilter.value && (item.status || '').toLowerCase() !== statusFilter.value.toLowerCase()) return false;
    return true;
  })
);

const fetchHistory = async (page = 1) => {
  loading.value = true;
  try {
    const res = await api.get('/admin/reports/downloads', { params: { page } });
    history.value = res.data.history || { data: [], total: 0, per_page: 20, current_page: 1, from: 0, to: 0, prev_page_url: null, next_page_url: null };
  } catch (e) {
    console.error('Failed to load downloads:', e);
  } finally {
    loading.value = false;
  }
};

const formatDate = (date) => {
  if (!date) return '';
  return new Date(date).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
};

const getFormatClass = (format) => {
  const map = { csv: 'bg-blue-900/50 text-blue-400', excel: 'bg-green-900/50 text-green-400', pdf: 'bg-red-900/50 text-red-400' };
  return map[format?.toLowerCase()] || 'bg-gray-900/50 text-gray-400';
};

const downloadReport = async (item) => {
  try {
    const response = await api.post('/admin/reports/export', {
      format: item.format,
      report_type: item.type,
      start_date: item.start_date,
      end_date: item.end_date,
    }, { responseType: 'blob' });
    const url = window.URL.createObjectURL(new Blob([response.data]));
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${item.name}.${item.format === 'excel' ? 'xlsx' : item.format}`);
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
  } catch (e) {
    console.error('Download failed:', e);
  }
};

const deleteReport = async (id) => {
  if (!confirm('Are you sure you want to delete this report?')) return;
  try {
    await api.delete(`/admin/reports/downloads/${id}`);
    fetchHistory(history.value.current_page);
  } catch (e) {
    console.error('Delete failed:', e);
  }
};

const changePage = (page) => {
  fetchHistory(page);
};

const resetFilters = () => {
  formatFilter.value = '';
  statusFilter.value = '';
};

onMounted(() => fetchHistory());
</script>